######################################################################
# Automatically generated by qmake (3.0) ?? ??? 22 18:52:33 2013
######################################################################

TEMPLATE = app
TARGET = Circles
INCLUDEPATH += .

# Input
HEADERS += Circle.h Point.h RenderArea.h Window.h
SOURCES += Circle.cpp main.cpp Point.cpp RenderArea.cpp Window.cpp
QT += widgets
